"""empty message

Revision ID: 41c2cf0fe4cc
Revises: 
Create Date: 2020-06-16 01:44:19.021807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c2cf0fe4cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=True),
    sa.Column('options', sa.String(length=256), nullable=True),
    sa.Column('correct', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_question'), 'quiz', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_question'), table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###
