"""empty message

Revision ID: 8cee5bea7c0b
Revises: 41c2cf0fe4cc
Create Date: 2020-06-16 01:59:02.936423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cee5bea7c0b'
down_revision = '41c2cf0fe4cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=128), nullable=True),
    sa.Column('options', sa.PickleType(), nullable=True),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_question'), 'question', ['question'], unique=True)
    op.drop_index('ix_quiz_question', table_name='quiz')
    op.drop_table('quiz')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=128), nullable=True),
    sa.Column('options', sa.VARCHAR(length=256), nullable=True),
    sa.Column('correct', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_question', 'quiz', ['question'], unique=1)
    op.drop_index(op.f('ix_question_question'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###
